POST http://localhost/suggestions
Content-Type: application/x-www-form-urlencoded
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTIxODA1MDIsInVzZXJuYW1lIjoicG91cnlhcGIifQ.3d9qcXsOorlR34SAanOKx7fRw02SA2HXeFeNy9zIOfo

text=sometext
